### ISSUE TITLE
dummy void-pointer probably unnecessary

### ISSUE THREAD

**Issue by skade** [ifesdjeen/rusty-pipes#1]
In:

https://github.com/ifesdjeen/rusty-pipes/blob/789b3798522661384be3b6978e10fca8db44ba59/src/main.rs#L18-L19

The idiomatic way to type opaque c structs is an enum with no variants:

```
pub enum sigar_t {};
```

This way, it cannot be constructed.

**Comment by ifesdjeen** [comment]
:) great stuff! thanks @skade!

**Comment by ifesdjeen** [comment]
fixed :)
